# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Benja\Source\Repos\Quantum158\SpeedController\modules\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 671)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setMouseTracking(False)
        MainWindow.setTabletTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.MainLayout = QtWidgets.QHBoxLayout()
        self.MainLayout.setObjectName("MainLayout")
        self.CenterPart = QtWidgets.QWidget(self.centralwidget)
        self.CenterPart.setEnabled(True)
        self.CenterPart.setObjectName("CenterPart")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.CenterPart)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ALayout = QtWidgets.QVBoxLayout()
        self.ALayout.setObjectName("ALayout")
        self.TimerALabel = QtWidgets.QLabel(self.CenterPart)
        self.TimerALabel.setStyleSheet("font: 40pt \"Calibri\";\n"
"text-decoration: underline;")
        self.TimerALabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TimerALabel.setObjectName("TimerALabel")
        self.ALayout.addWidget(self.TimerALabel)
        self.AFalseStart = QtWidgets.QPushButton(self.CenterPart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AFalseStart.sizePolicy().hasHeightForWidth())
        self.AFalseStart.setSizePolicy(sizePolicy)
        self.AFalseStart.setMinimumSize(QtCore.QSize(0, 58))
        self.AFalseStart.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.AFalseStart.setObjectName("AFalseStart")
        self.ALayout.addWidget(self.AFalseStart)
        self.AColourDisplay = QtWidgets.QWidget(self.CenterPart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AColourDisplay.sizePolicy().hasHeightForWidth())
        self.AColourDisplay.setSizePolicy(sizePolicy)
        self.AColourDisplay.setObjectName("AColourDisplay")
        self.ALayout.addWidget(self.AColourDisplay)
        self.AStopTime = QtWidgets.QPushButton(self.CenterPart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AStopTime.sizePolicy().hasHeightForWidth())
        self.AStopTime.setSizePolicy(sizePolicy)
        self.AStopTime.setMinimumSize(QtCore.QSize(0, 58))
        self.AStopTime.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"alternate-background-color: rgb(85, 255, 255);")
        self.AStopTime.setObjectName("AStopTime")
        self.ALayout.addWidget(self.AStopTime)
        self.TimerATime = QtWidgets.QLabel(self.CenterPart)
        self.TimerATime.setStyleSheet("font: 40pt \"Calibri\";")
        self.TimerATime.setAlignment(QtCore.Qt.AlignCenter)
        self.TimerATime.setObjectName("TimerATime")
        self.ALayout.addWidget(self.TimerATime)
        self.horizontalLayout_3.addLayout(self.ALayout)
        self.ACenterLine = QtWidgets.QFrame(self.CenterPart)
        self.ACenterLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ACenterLine.setLineWidth(3)
        self.ACenterLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.ACenterLine.setObjectName("ACenterLine")
        self.horizontalLayout_3.addWidget(self.ACenterLine)
        self.CenterLayout = QtWidgets.QVBoxLayout()
        self.CenterLayout.setObjectName("CenterLayout")
        self.StatusLabel = QtWidgets.QLabel(self.CenterPart)
        self.StatusLabel.setStyleSheet("font: 40pt \"Calibri\";\n"
"text-decoration: underline;")
        self.StatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.StatusLabel.setObjectName("StatusLabel")
        self.CenterLayout.addWidget(self.StatusLabel)
        self.StatusControlLineSep_3 = QtWidgets.QFrame(self.CenterPart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StatusControlLineSep_3.sizePolicy().hasHeightForWidth())
        self.StatusControlLineSep_3.setSizePolicy(sizePolicy)
        self.StatusControlLineSep_3.setMinimumSize(QtCore.QSize(0, 0))
        self.StatusControlLineSep_3.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.StatusControlLineSep_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.StatusControlLineSep_3.setLineWidth(7)
        self.StatusControlLineSep_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.StatusControlLineSep_3.setObjectName("StatusControlLineSep_3")
        self.CenterLayout.addWidget(self.StatusControlLineSep_3)
        self.textStatus = QtWidgets.QLabel(self.CenterPart)
        self.textStatus.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.textStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.textStatus.setObjectName("textStatus")
        self.CenterLayout.addWidget(self.textStatus)
        self.StatusControlLineSep_2 = QtWidgets.QFrame(self.CenterPart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StatusControlLineSep_2.sizePolicy().hasHeightForWidth())
        self.StatusControlLineSep_2.setSizePolicy(sizePolicy)
        self.StatusControlLineSep_2.setMinimumSize(QtCore.QSize(0, 0))
        self.StatusControlLineSep_2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.StatusControlLineSep_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.StatusControlLineSep_2.setLineWidth(7)
        self.StatusControlLineSep_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.StatusControlLineSep_2.setObjectName("StatusControlLineSep_2")
        self.CenterLayout.addWidget(self.StatusControlLineSep_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.CenterLayout.addItem(spacerItem)
        self.StatusControlLineSep = QtWidgets.QFrame(self.CenterPart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StatusControlLineSep.sizePolicy().hasHeightForWidth())
        self.StatusControlLineSep.setSizePolicy(sizePolicy)
        self.StatusControlLineSep.setMinimumSize(QtCore.QSize(0, 0))
        self.StatusControlLineSep.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.StatusControlLineSep.setFrameShadow(QtWidgets.QFrame.Plain)
        self.StatusControlLineSep.setLineWidth(7)
        self.StatusControlLineSep.setFrameShape(QtWidgets.QFrame.HLine)
        self.StatusControlLineSep.setObjectName("StatusControlLineSep")
        self.CenterLayout.addWidget(self.StatusControlLineSep)
        self.pushController = QtWidgets.QPushButton(self.CenterPart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushController.sizePolicy().hasHeightForWidth())
        self.pushController.setSizePolicy(sizePolicy)
        self.pushController.setMinimumSize(QtCore.QSize(0, 80))
        self.pushController.setStyleSheet("font: 25pt \"MS Shell Dlg 2\";")
        self.pushController.setIconSize(QtCore.QSize(16, 16))
        self.pushController.setCheckable(False)
        self.pushController.setChecked(False)
        self.pushController.setAutoDefault(False)
        self.pushController.setDefault(False)
        self.pushController.setFlat(False)
        self.pushController.setObjectName("pushController")
        self.CenterLayout.addWidget(self.pushController)
        self.ControllOptionLineSep = QtWidgets.QFrame(self.CenterPart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ControllOptionLineSep.sizePolicy().hasHeightForWidth())
        self.ControllOptionLineSep.setSizePolicy(sizePolicy)
        self.ControllOptionLineSep.setMinimumSize(QtCore.QSize(0, 0))
        self.ControllOptionLineSep.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ControllOptionLineSep.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.ControllOptionLineSep.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ControllOptionLineSep.setLineWidth(7)
        self.ControllOptionLineSep.setMidLineWidth(0)
        self.ControllOptionLineSep.setFrameShape(QtWidgets.QFrame.HLine)
        self.ControllOptionLineSep.setObjectName("ControllOptionLineSep")
        self.CenterLayout.addWidget(self.ControllOptionLineSep)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.CenterLayout.addItem(spacerItem1)
        self.OptionsLabel = QtWidgets.QLabel(self.CenterPart)
        self.OptionsLabel.setStyleSheet("font: 40pt \"Calibri\";\n"
"text-decoration: underline;")
        self.OptionsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.OptionsLabel.setObjectName("OptionsLabel")
        self.CenterLayout.addWidget(self.OptionsLabel)
        self.OptionsGrid = QtWidgets.QGridLayout()
        self.OptionsGrid.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.OptionsGrid.setObjectName("OptionsGrid")
        self.RecordSpin = QtWidgets.QSpinBox(self.CenterPart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RecordSpin.sizePolicy().hasHeightForWidth())
        self.RecordSpin.setSizePolicy(sizePolicy)
        self.RecordSpin.setKeyboardTracking(True)
        self.RecordSpin.setDisplayIntegerBase(10)
        self.RecordSpin.setObjectName("RecordSpin")
        self.OptionsGrid.addWidget(self.RecordSpin, 4, 3, 1, 1)
        self.checkGoProCommands = QtWidgets.QCheckBox(self.CenterPart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkGoProCommands.sizePolicy().hasHeightForWidth())
        self.checkGoProCommands.setSizePolicy(sizePolicy)
        self.checkGoProCommands.setObjectName("checkGoProCommands")
        self.OptionsGrid.addWidget(self.checkGoProCommands, 3, 1, 1, 1)
        self.checkATimerEnable = QtWidgets.QCheckBox(self.CenterPart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkATimerEnable.sizePolicy().hasHeightForWidth())
        self.checkATimerEnable.setSizePolicy(sizePolicy)
        self.checkATimerEnable.setObjectName("checkATimerEnable")
        self.OptionsGrid.addWidget(self.checkATimerEnable, 1, 1, 1, 1)
        self.StageDelaySpin = QtWidgets.QSpinBox(self.CenterPart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StageDelaySpin.sizePolicy().hasHeightForWidth())
        self.StageDelaySpin.setSizePolicy(sizePolicy)
        self.StageDelaySpin.setPrefix("")
        self.StageDelaySpin.setObjectName("StageDelaySpin")
        self.OptionsGrid.addWidget(self.StageDelaySpin, 8, 3, 1, 1)
        self.OptionsLine1 = QtWidgets.QFrame(self.CenterPart)
        self.OptionsLine1.setMinimumSize(QtCore.QSize(15, 15))
        self.OptionsLine1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.OptionsLine1.setLineWidth(2)
        self.OptionsLine1.setMidLineWidth(0)
        self.OptionsLine1.setFrameShape(QtWidgets.QFrame.HLine)
        self.OptionsLine1.setObjectName("OptionsLine1")
        self.OptionsGrid.addWidget(self.OptionsLine1, 7, 1, 1, 3)
        self.checkBTimerEnable = QtWidgets.QCheckBox(self.CenterPart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBTimerEnable.sizePolicy().hasHeightForWidth())
        self.checkBTimerEnable.setSizePolicy(sizePolicy)
        self.checkBTimerEnable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBTimerEnable.setIconSize(QtCore.QSize(16, 16))
        self.checkBTimerEnable.setObjectName("checkBTimerEnable")
        self.OptionsGrid.addWidget(self.checkBTimerEnable, 1, 3, 1, 1)
        self.OptionsLine0 = QtWidgets.QFrame(self.CenterPart)
        self.OptionsLine0.setMinimumSize(QtCore.QSize(15, 15))
        self.OptionsLine0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.OptionsLine0.setLineWidth(2)
        self.OptionsLine0.setMidLineWidth(0)
        self.OptionsLine0.setFrameShape(QtWidgets.QFrame.HLine)
        self.OptionsLine0.setObjectName("OptionsLine0")
        self.OptionsGrid.addWidget(self.OptionsLine0, 2, 1, 1, 3)
        self.GoProWarningBeeps = QtWidgets.QCheckBox(self.CenterPart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GoProWarningBeeps.sizePolicy().hasHeightForWidth())
        self.GoProWarningBeeps.setSizePolicy(sizePolicy)
        self.GoProWarningBeeps.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.GoProWarningBeeps.setObjectName("GoProWarningBeeps")
        self.OptionsGrid.addWidget(self.GoProWarningBeeps, 3, 3, 1, 1)
        self.PacerBeepsSpin = QtWidgets.QSpinBox(self.CenterPart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PacerBeepsSpin.sizePolicy().hasHeightForWidth())
        self.PacerBeepsSpin.setSizePolicy(sizePolicy)
        self.PacerBeepsSpin.setKeyboardTracking(True)
        self.PacerBeepsSpin.setObjectName("PacerBeepsSpin")
        self.OptionsGrid.addWidget(self.PacerBeepsSpin, 10, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.OptionsGrid.addItem(spacerItem2, 1, 2, 1, 1)
        self.OptionsLine2 = QtWidgets.QFrame(self.CenterPart)
        self.OptionsLine2.setMinimumSize(QtCore.QSize(15, 15))
        self.OptionsLine2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.OptionsLine2.setLineWidth(2)
        self.OptionsLine2.setMidLineWidth(0)
        self.OptionsLine2.setFrameShape(QtWidgets.QFrame.HLine)
        self.OptionsLine2.setObjectName("OptionsLine2")
        self.OptionsGrid.addWidget(self.OptionsLine2, 9, 1, 1, 3)
        self.RecordStopLabel = QtWidgets.QLabel(self.CenterPart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RecordStopLabel.sizePolicy().hasHeightForWidth())
        self.RecordStopLabel.setSizePolicy(sizePolicy)
        self.RecordStopLabel.setObjectName("RecordStopLabel")
        self.OptionsGrid.addWidget(self.RecordStopLabel, 4, 1, 1, 2)
        self.OptionsLine3 = QtWidgets.QFrame(self.CenterPart)
        self.OptionsLine3.setMinimumSize(QtCore.QSize(15, 15))
        self.OptionsLine3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.OptionsLine3.setLineWidth(2)
        self.OptionsLine3.setMidLineWidth(0)
        self.OptionsLine3.setFrameShape(QtWidgets.QFrame.HLine)
        self.OptionsLine3.setObjectName("OptionsLine3")
        self.OptionsGrid.addWidget(self.OptionsLine3, 11, 1, 1, 3)
        self.delayAfterStagingLabel = QtWidgets.QLabel(self.CenterPart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delayAfterStagingLabel.sizePolicy().hasHeightForWidth())
        self.delayAfterStagingLabel.setSizePolicy(sizePolicy)
        self.delayAfterStagingLabel.setObjectName("delayAfterStagingLabel")
        self.OptionsGrid.addWidget(self.delayAfterStagingLabel, 8, 1, 1, 2)
        self.PacerLabel = QtWidgets.QLabel(self.CenterPart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PacerLabel.sizePolicy().hasHeightForWidth())
        self.PacerLabel.setSizePolicy(sizePolicy)
        self.PacerLabel.setObjectName("PacerLabel")
        self.OptionsGrid.addWidget(self.PacerLabel, 10, 1, 1, 2)
        self.OpenLogPush = QtWidgets.QPushButton(self.CenterPart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OpenLogPush.sizePolicy().hasHeightForWidth())
        self.OpenLogPush.setSizePolicy(sizePolicy)
        self.OpenLogPush.setObjectName("OpenLogPush")
        self.OptionsGrid.addWidget(self.OpenLogPush, 12, 1, 1, 3)
        self.CenterLayout.addLayout(self.OptionsGrid)
        self.horizontalLayout_3.addLayout(self.CenterLayout)
        self.CenterBLin = QtWidgets.QFrame(self.CenterPart)
        self.CenterBLin.setFrameShadow(QtWidgets.QFrame.Plain)
        self.CenterBLin.setLineWidth(3)
        self.CenterBLin.setFrameShape(QtWidgets.QFrame.VLine)
        self.CenterBLin.setObjectName("CenterBLin")
        self.horizontalLayout_3.addWidget(self.CenterBLin)
        self.BLayout = QtWidgets.QVBoxLayout()
        self.BLayout.setObjectName("BLayout")
        self.TimerBLabel = QtWidgets.QLabel(self.CenterPart)
        self.TimerBLabel.setStyleSheet("font: 40pt \"Calibri\";\n"
"text-decoration: underline;")
        self.TimerBLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TimerBLabel.setObjectName("TimerBLabel")
        self.BLayout.addWidget(self.TimerBLabel)
        self.BFalseStart = QtWidgets.QPushButton(self.CenterPart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BFalseStart.sizePolicy().hasHeightForWidth())
        self.BFalseStart.setSizePolicy(sizePolicy)
        self.BFalseStart.setMinimumSize(QtCore.QSize(0, 58))
        self.BFalseStart.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.BFalseStart.setObjectName("BFalseStart")
        self.BLayout.addWidget(self.BFalseStart)
        self.BColourDisplay = QtWidgets.QWidget(self.CenterPart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BColourDisplay.sizePolicy().hasHeightForWidth())
        self.BColourDisplay.setSizePolicy(sizePolicy)
        self.BColourDisplay.setObjectName("BColourDisplay")
        self.BLayout.addWidget(self.BColourDisplay)
        self.BStopTime = QtWidgets.QPushButton(self.CenterPart)
        self.BStopTime.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BStopTime.sizePolicy().hasHeightForWidth())
        self.BStopTime.setSizePolicy(sizePolicy)
        self.BStopTime.setMinimumSize(QtCore.QSize(0, 58))
        self.BStopTime.setAutoFillBackground(False)
        self.BStopTime.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.BStopTime.setAutoDefault(False)
        self.BStopTime.setDefault(False)
        self.BStopTime.setFlat(False)
        self.BStopTime.setObjectName("BStopTime")
        self.BLayout.addWidget(self.BStopTime)
        self.TimerBTime = QtWidgets.QLabel(self.CenterPart)
        self.TimerBTime.setStyleSheet("font: 40pt \"Calibri\";\n"
"")
        self.TimerBTime.setAlignment(QtCore.Qt.AlignCenter)
        self.TimerBTime.setObjectName("TimerBTime")
        self.BLayout.addWidget(self.TimerBTime)
        self.horizontalLayout_3.addLayout(self.BLayout)
        self.MainLayout.addWidget(self.CenterPart)
        self.gridLayout.addLayout(self.MainLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Speed Controller"))
        self.TimerALabel.setText(_translate("MainWindow", "Timer A"))
        self.AFalseStart.setText(_translate("MainWindow", "False Start\n"
"(Shift+Left Arrow)"))
        self.AStopTime.setText(_translate("MainWindow", "Stop Time\n"
"(Left Arrow)"))
        self.TimerATime.setText(_translate("MainWindow", "0:00.00"))
        self.StatusLabel.setText(_translate("MainWindow", "Status"))
        self.textStatus.setText(_translate("MainWindow", "Ready..."))
        self.pushController.setText(_translate("MainWindow", "Start"))
        self.OptionsLabel.setText(_translate("MainWindow", "Options"))
        self.RecordSpin.setToolTip(_translate("MainWindow", "<html><head/><body><p>Camera will automatically stop recording this many seconds after climbing has started</p><p>(Note: This setting is based on when the climb begins. The camera starts recording ~4 seconds before climbing, this is not included)</p><p>Setting this value to `0` will disable the system from automatically stopping the camera</p></body></html>"))
        self.RecordSpin.setSuffix(_translate("MainWindow", "   Seconds"))
        self.checkGoProCommands.setText(_translate("MainWindow", "Use GoPro"))
        self.checkATimerEnable.setText(_translate("MainWindow", "Timer A Enabled"))
        self.StageDelaySpin.setToolTip(_translate("MainWindow", "<html><head/><body><p>System will wait said time after start is pressed before playing the start tones</p></body></html>"))
        self.StageDelaySpin.setSuffix(_translate("MainWindow", "   Seconds"))
        self.checkBTimerEnable.setText(_translate("MainWindow", "Timer B Enabled"))
        self.GoProWarningBeeps.setText(_translate("MainWindow", "Warning Beeps"))
        self.PacerBeepsSpin.setToolTip(_translate("MainWindow", "<html><head/><body><p>&lt;SOMEONE NEEDS TO HELP ME DESCRIBE THIS&gt;</p></body></html>"))
        self.PacerBeepsSpin.setSuffix(_translate("MainWindow", "   Seconds"))
        self.RecordStopLabel.setText(_translate("MainWindow", "Automatic Record Stop"))
        self.delayAfterStagingLabel.setText(_translate("MainWindow", "Delay After Staging"))
        self.PacerLabel.setText(_translate("MainWindow", "Pacer Beeps"))
        self.OpenLogPush.setText(_translate("MainWindow", "Open Log"))
        self.TimerBLabel.setText(_translate("MainWindow", "Timer B"))
        self.BFalseStart.setText(_translate("MainWindow", "False Start\n"
"(Shift+Right Arrow)"))
        self.BStopTime.setText(_translate("MainWindow", "Stop Time\n"
"(Right Arrow)"))
        self.TimerBTime.setText(_translate("MainWindow", "0:00.00"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

