# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Benja\source\repos\Quantum158\SpeedController\V2\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setMouseTracking(False)
        MainWindow.setTabletTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 621))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.widget.setObjectName("widget")
        self.TimerALabel = QtWidgets.QLabel(self.widget)
        self.TimerALabel.setGeometry(QtCore.QRect(0, 0, 261, 51))
        self.TimerALabel.setStyleSheet("font: 40pt \"Calibri\";\n"
"text-decoration: underline;")
        self.TimerALabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TimerALabel.setObjectName("TimerALabel")
        self.TimerATime = QtWidgets.QLabel(self.widget)
        self.TimerATime.setGeometry(QtCore.QRect(0, 530, 261, 51))
        self.TimerATime.setStyleSheet("font: 40pt \"Calibri\";")
        self.TimerATime.setAlignment(QtCore.Qt.AlignCenter)
        self.TimerATime.setObjectName("TimerATime")
        self.AFalseStart = QtWidgets.QPushButton(self.widget)
        self.AFalseStart.setGeometry(QtCore.QRect(30, 70, 201, 61))
        self.AFalseStart.setStyleSheet("font: 16pt \"MS Shell Dlg 2\"; background-color: rgb(190, 190, 190);")
        self.AFalseStart.setObjectName("AFalseStart")
        self.AStopTime = QtWidgets.QPushButton(self.widget)
        self.AStopTime.setGeometry(QtCore.QRect(30, 460, 201, 61))
        self.AStopTime.setStyleSheet("font: 16pt \"MS Shell Dlg 2\"; background-color: rgb(190, 190, 190);")
        self.AStopTime.setObjectName("AStopTime")
        self.horizontalLayout_3.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget_3.setObjectName("widget_3")
        self.StatusLabel = QtWidgets.QLabel(self.widget_3)
        self.StatusLabel.setGeometry(QtCore.QRect(0, 0, 261, 51))
        self.StatusLabel.setStyleSheet("font: 40pt \"Calibri\";\n"
"text-decoration: underline;")
        self.StatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.StatusLabel.setObjectName("StatusLabel")
        self.textStatus = QtWidgets.QLabel(self.widget_3)
        self.textStatus.setGeometry(QtCore.QRect(10, 60, 241, 81))
        self.textStatus.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.textStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.textStatus.setObjectName("textStatus")
        self.line = QtWidgets.QFrame(self.widget_3)
        self.line.setGeometry(QtCore.QRect(0, 140, 261, 21))
        self.line.setMinimumSize(QtCore.QSize(0, 0))
        self.line.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.line.setLineWidth(7)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushController = QtWidgets.QPushButton(self.widget_3)
        self.pushController.setGeometry(QtCore.QRect(30, 190, 201, 61))
        self.pushController.setStyleSheet("font: 25pt \"MS Shell Dlg 2\";")
        self.pushController.setObjectName("pushController")
        self.line_2 = QtWidgets.QFrame(self.widget_3)
        self.line_2.setGeometry(QtCore.QRect(0, 290, 261, 21))
        self.line_2.setMinimumSize(QtCore.QSize(0, 0))
        self.line_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.line_2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.line_2.setLineWidth(7)
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.OptionsLabel = QtWidgets.QLabel(self.widget_3)
        self.OptionsLabel.setGeometry(QtCore.QRect(0, 320, 261, 51))
        self.OptionsLabel.setStyleSheet("font: 40pt \"Calibri\";\n"
"text-decoration: underline;")
        self.OptionsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.OptionsLabel.setObjectName("OptionsLabel")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.widget_3)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 380, 261, 167))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.checkATimerEnable = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.checkATimerEnable.setObjectName("checkATimerEnable")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkATimerEnable)
        self.checkBTimerEnable = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.checkBTimerEnable.setObjectName("checkBTimerEnable")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkBTimerEnable)
        self.delayAfterStagingLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.delayAfterStagingLabel.setObjectName("delayAfterStagingLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.delayAfterStagingLabel)
        self.line_3 = QtWidgets.QFrame(self.formLayoutWidget_2)
        self.line_3.setMinimumSize(QtCore.QSize(15, 15))
        self.line_3.setLineWidth(100)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.line_3)
        self.checkDelayLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.checkDelayLabel.setObjectName("checkDelayLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.checkDelayLabel)
        self.cooldownDelayLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.cooldownDelayLabel.setObjectName("cooldownDelayLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.cooldownDelayLabel)
        self.StageDelaySpin = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.StageDelaySpin.setObjectName("StageDelaySpin")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.StageDelaySpin)
        self.CheckDelaySpin = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.CheckDelaySpin.setObjectName("CheckDelaySpin")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.CheckDelaySpin)
        self.CooldownSpin = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.CooldownSpin.setObjectName("CooldownSpin")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.CooldownSpin)
        self.horizontalLayout_3.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.widget_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.widget_2.setObjectName("widget_2")
        self.TimerBLabel = QtWidgets.QLabel(self.widget_2)
        self.TimerBLabel.setGeometry(QtCore.QRect(0, 0, 261, 51))
        self.TimerBLabel.setStyleSheet("font: 40pt \"Calibri\";\n"
"text-decoration: underline;")
        self.TimerBLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TimerBLabel.setObjectName("TimerBLabel")
        self.TimerBTime = QtWidgets.QLabel(self.widget_2)
        self.TimerBTime.setGeometry(QtCore.QRect(0, 530, 261, 51))
        self.TimerBTime.setStyleSheet("font: 40pt \"Calibri\";\n"
"")
        self.TimerBTime.setAlignment(QtCore.Qt.AlignCenter)
        self.TimerBTime.setObjectName("TimerBTime")
        self.BStopTime = QtWidgets.QPushButton(self.widget_2)
        self.BStopTime.setEnabled(True)
        self.BStopTime.setGeometry(QtCore.QRect(30, 460, 201, 61))
        self.BStopTime.setAutoFillBackground(False)
        self.BStopTime.setStyleSheet("font: 16pt \"MS Shell Dlg 2\"; background-color: rgb(190, 190, 190);")
        self.BStopTime.setAutoDefault(False)
        self.BStopTime.setDefault(False)
        self.BStopTime.setFlat(False)
        self.BStopTime.setObjectName("BStopTime")
        self.BFalseStart = QtWidgets.QPushButton(self.widget_2)
        self.BFalseStart.setGeometry(QtCore.QRect(40, 70, 201, 61))
        self.BFalseStart.setStyleSheet("font: 16pt \"MS Shell Dlg 2\"; background-color: rgb(190, 190, 190);")
        self.BFalseStart.setObjectName("BFalseStart")
        self.horizontalLayout_3.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionOptions = QtWidgets.QAction(MainWindow)
        self.actionOptions.setObjectName("actionOptions")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TimerALabel.setText(_translate("MainWindow", "Timer A"))
        self.TimerATime.setText(_translate("MainWindow", "0:00.00"))
        self.AFalseStart.setText(_translate("MainWindow", "False Start\n"
"(Shift+Left Arrow)"))
        self.AStopTime.setText(_translate("MainWindow", "Stop Time\n"
"(Left Arrow)"))
        self.StatusLabel.setText(_translate("MainWindow", "Status"))
        self.textStatus.setText(_translate("MainWindow", "Ready..."))
        self.pushController.setText(_translate("MainWindow", "Start"))
        self.OptionsLabel.setText(_translate("MainWindow", "Options"))
        self.checkATimerEnable.setText(_translate("MainWindow", "Timer A Enabled"))
        self.checkBTimerEnable.setText(_translate("MainWindow", "Timer B Enabled"))
        self.delayAfterStagingLabel.setText(_translate("MainWindow", "Delay After Staging"))
        self.checkDelayLabel.setText(_translate("MainWindow", "Start Check Delay"))
        self.cooldownDelayLabel.setText(_translate("MainWindow", "Cooldown Delay"))
        self.TimerBLabel.setText(_translate("MainWindow", "Timer B"))
        self.TimerBTime.setText(_translate("MainWindow", "0:00.00"))
        self.BStopTime.setText(_translate("MainWindow", "Stop Time\n"
"(Right Arrow)"))
        self.BFalseStart.setText(_translate("MainWindow", "False Start\n"
"(Shift+Right Arrow)"))
        self.actionOptions.setText(_translate("MainWindow", "Options"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

